cpan App::cpanminus
cpanm local::lib
cpanm utf8::all
cpanm Carp
cpanm Data::Printer
cpanm English
cpanm YAML::XS
cpanm File::Basename
cpanm File::Path
cpanm File::Slurper
cpanm File::Temp
cpanm IPC::System::Simple    
cpanm JSON
cpanm List::MoreUtils
cpanm Path::Tiny
cpanm Sort::Key::Natural   
cpanm Try::Tiny
cpanm XML::Parser
cpanm XML::Tidy           
cpanm XML::Writer
cpanm XML::LibXML
cpanm YAML::XS